version: '3'
services:
  redis:
    image: "redis:5.0-rc4"
    container_name: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    build: .  
    ports:
     - "3800:3800"
    depends_on:
     - redis
